[package]
name = "server"
version = "0.1.0"
authors = ["Rodrigo Tanaka <krodrigo71008@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
rocket_contrib = "0.4.4"
